image: node:lts-alpine

.cache:
  cache:
    paths:
      - node_modules/

stages:
  - prepare
  - build
  - release

lint:
  stage: prepare
  extends: .cache
  allow_failure: true
  before_script:
    - npm set registry https://registry.npmmirror.com/
    - npm install -g pnpm
    - pnpm set registry https://registry.npmmirror.com/
    - pnpm install
  script:
    - pnpm lint

build:
  stage: build
  extends: .cache
  before_script:
    - npm set registry https://registry.npmmirror.com/
    - npm install -g pnpm
    - pnpm set registry https://registry.npmmirror.com/
    - pnpm install
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
    - apk add --no-cache zip
  script:
    - cp .env.production .env
    - cp settings/proxy-config.ts.example settings/proxy-config.ts
    - pnpm dev &
    - sleep 10
    - kill %1
    - pnpm build
    - zip -r dist.zip dist
  artifacts:
    name: "dist"
    paths:
      - dist.zip
    expire_in: 3 days

upload:
  stage: release
  image: curlimages/curl:latest
  only:
    - tags
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist.zip "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/dist.zip"

release:
  stage: release
  image: chenio/release-cli:latest
  only:
    - tags
  script:
    - |
      release-cli --server-url ${CI_SERVER_URL} create --name "$CI_COMMIT_TAG" --description "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"dist.zip\",\"url\":\"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/dist.zip\"}"   
